[project]
authors = [
  {name = "fmdtools Developers"},
]
maintainers = [
  {name = "Daniel Hulse", email = "daniel.e.hulse@nasa.gov"}
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
]
description = "System resilience modelling, simulation, and assessment in Python"
license = {file="LICENSE"}
name = "fmdtools"
version="2.4.0"
readme = "README.md"
requires-python = ">=3.12"

dependencies = ["scipy",
                "tqdm",
                "networkx",
                "numpy >= 2.0",
                "matplotlib >= 3.7.0",
                "pandas[plot, output-formatting] >= 2.2.0",
                "ordered-set",
                "dill",
                "recordclass == 0.24",
                "pytest",
                "graphviz",
                "shapely >= 2.0"
]

[project.optional-dependencies]
examples = ["deap", "pymoo", "scikit-learn", "multiprocess", "pathos", "adjustText", "jinja2"]
all = ["fmdtools[examples]"]

[project.urls]
Documentation = "https://nasa.github.io/fmdtools/"
source-code = "https://github.com/nasa/fmdtools"


[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61.0.0"
]

[dependency-groups]
docs = ["sphinx", "myst-nb", "sphinx_rtd_theme", "nbsphinx", "myst-sphinx-gallery"]
test = ["nbmake", "pytest-html", "coverage", "pytest-cov", "genbadge[all]"]
dev = [{include-group = "docs"}, {include-group = "test"}]

[tool.uv]
required-environments = ["sys_platform == 'win32' and platform_machine == 'AMD64'"]


[tool.pytest.ini_options]
addopts = "--cache-clear --import-mode=importlib --doctest-modules --nbmake --cov='src/fmdtools'"
pythonpath = ["src", "tests", "examples"]
norecursedirs = ["docs", "_build", "build", "tmp*", "jupyter_execute", "venv", ".venv"]

[tool.setuptools.package-dir]
fmdtools = "src/fmdtools"
fmdtools_examples = "examples"
fmdtools_tests = "tests"


[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "raise ",
    "if 0:",
    "if __name__ == .__main__.:",
	"def script_"
    ]
omit = [
    # omit everything in /build
    "/_build/*",
    "/docs/*",
    "*.pyc",
    "*/__pycache__/*",
    "*/tmp/*",
    # omit overall test
    "run_all_tests.py",
    "conftest.py",
    "*/__init__.py",
    "*/ipykernel*",
    "*/Temp/*"
    ]

[tool.coverage.run]
omit = [
    # omit everything in /build
    "/_build/*",
    "/docs/*",
    "*.pyc",
    "*/__pycache__/*",
    "*/tmp/*",
    # omit overall test
    "run_all_tests.py",
    "*/__init__.py",
    "*/ipykernel*",
    "*/Temp/*"
    ]

